export const coreStatements = [
  "CREATE EXTENSION IF NOT EXISTS pgcrypto;",

  `CREATE TABLE IF NOT EXISTS customers (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    phone text,
    email text,
    street_address text,
    city text,
    state_code text,
    zip text,
    latitude numeric(10,7),
    longitude numeric(10,7),
    customer_source text NOT NULL DEFAULT 'unknown',
    referral_source text,
    priority_tier text NOT NULL DEFAULT 'B',
    notes text,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT customers_priority_tier_chk CHECK (priority_tier IN ('A','B','C')),
    CONSTRAINT customers_deleted_at_chk CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL))
  );`,
  "CREATE UNIQUE INDEX IF NOT EXISTS customers_phone_uq ON customers(phone) WHERE is_deleted = false;",

  `CREATE TABLE IF NOT EXISTS leads (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    phone text,
    email text,
    street_address text,
    city text,
    state_code text,
    zip text,
    lead_source text NOT NULL DEFAULT 'unknown',
    lead_score integer,
    status text NOT NULL DEFAULT 'new',
    call_transcript text,
    ai_summary text,
    qualifying_data jsonb,
    converted_to_customer_id uuid REFERENCES customers(id) ON DELETE SET NULL,
    converted_at timestamptz,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT leads_status_chk CHECK (status IN ('new','contacted','qualified','converted','lost')),
    CONSTRAINT leads_deleted_at_chk CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL))
  );`,
  "CREATE INDEX IF NOT EXISTS leads_converted_to_customer_id_idx ON leads(converted_to_customer_id);",

  `CREATE TABLE IF NOT EXISTS employees (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    email text,
    phone text,
    role text NOT NULL DEFAULT 'technician',
    permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
    pay_type text NOT NULL DEFAULT 'hourly',
    hourly_rate numeric(12,2),
    salary_annual numeric(12,2),
    hire_date date NOT NULL DEFAULT CURRENT_DATE,
    termination_date date,
    is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT employees_role_chk CHECK (role IN ('owner','admin','technician')),
    CONSTRAINT employees_pay_type_chk CHECK (pay_type IN ('hourly','salary')),
    CONSTRAINT employees_pay_fields_chk CHECK (
      (pay_type = 'hourly' AND hourly_rate IS NOT NULL AND salary_annual IS NULL)
      OR
      (pay_type = 'salary' AND salary_annual IS NOT NULL)
    ),
    CONSTRAINT employees_deleted_at_chk CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL))
  );`,
  "CREATE UNIQUE INDEX IF NOT EXISTS employees_email_uq ON employees(email) WHERE email IS NOT NULL AND is_deleted = false;",

  `CREATE TABLE IF NOT EXISTS vendors (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    category text NOT NULL DEFAULT 'supplier',
    default_expense_type text,
    payment_terms text NOT NULL DEFAULT 'due_on_receipt',
    street_address text,
    city text,
    state_code text,
    zip text,
    phone text,
    email text,
    account_number text,
    notes text,
    is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT vendors_category_chk CHECK (category IN ('supplier','fuel','equipment','service','subcontractor','other')),
    CONSTRAINT vendors_terms_chk CHECK (payment_terms IN ('net_30','net_15','due_on_receipt')),
    CONSTRAINT vendors_deleted_at_chk CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL))
  );`,
  "CREATE UNIQUE INDEX IF NOT EXISTS vendors_name_uq ON vendors(lower(name)) WHERE is_deleted = false;",
];
