export const expensesStatements = [
  `CREATE TABLE IF NOT EXISTS job_expenses (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE RESTRICT,
    vendor_id uuid NOT NULL REFERENCES vendors(id) ON DELETE RESTRICT,
    employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,
    expense_type text NOT NULL DEFAULT 'materials',
    amount numeric(12,2) NOT NULL,
    tax_amount numeric(12,2) NOT NULL DEFAULT 0,
    total_amount numeric(12,2) GENERATED ALWAYS AS (round(amount + tax_amount, 2)) STORED,
    expense_date date NOT NULL DEFAULT CURRENT_DATE,
    receipt_photo_url text,
    receipt_parsed_data jsonb,
    auto_categorized boolean NOT NULL DEFAULT false,
    description text,
    status text NOT NULL DEFAULT 'pending',
    approved_by_employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,
    approved_at timestamptz,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT job_expenses_type_chk CHECK (expense_type IN ('materials','subcontractor','permits','disposal','other')),
    CONSTRAINT job_expenses_amount_chk CHECK (amount > 0),
    CONSTRAINT job_expenses_tax_chk CHECK (tax_amount >= 0),
    CONSTRAINT job_expenses_status_chk CHECK (status IN ('pending','approved','rejected','posted')),
    CONSTRAINT job_expenses_approved_chk CHECK ((status <> 'approved' AND approved_at IS NULL) OR (status = 'approved' AND approved_at IS NOT NULL)),
    CONSTRAINT job_expenses_deleted_at_chk CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL))
  );`,
  "CREATE INDEX IF NOT EXISTS job_expenses_job_id_idx ON job_expenses(job_id);",
  "CREATE INDEX IF NOT EXISTS job_expenses_vendor_id_idx ON job_expenses(vendor_id);",

  `CREATE TABLE IF NOT EXISTS chart_of_accounts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    account_number text NOT NULL,
    account_name text NOT NULL,
    account_type text NOT NULL,
    account_subtype text,
    parent_account_id uuid REFERENCES chart_of_accounts(id) ON DELETE SET NULL,
    normal_balance text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    is_system boolean NOT NULL DEFAULT false,
    sort_order integer,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chart_of_accounts_type_chk CHECK (account_type IN ('asset','liability','equity','revenue','expense')),
    CONSTRAINT chart_of_accounts_balance_chk CHECK (normal_balance IN ('debit','credit')),
    CONSTRAINT chart_of_accounts_deleted_at_chk CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL)),
    CONSTRAINT chart_of_accounts_account_number_uq UNIQUE (account_number)
  );`,

  `CREATE TABLE IF NOT EXISTS general_expenses (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    vendor_id uuid NOT NULL REFERENCES vendors(id) ON DELETE RESTRICT,
    employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,
    account_id uuid NOT NULL REFERENCES chart_of_accounts(id) ON DELETE RESTRICT,
    expense_type text NOT NULL DEFAULT 'other',
    amount numeric(12,2) NOT NULL,
    tax_amount numeric(12,2) NOT NULL DEFAULT 0,
    total_amount numeric(12,2) GENERATED ALWAYS AS (round(amount + tax_amount, 2)) STORED,
    expense_date date NOT NULL DEFAULT CURRENT_DATE,
    receipt_photo_url text,
    receipt_parsed_data jsonb,
    auto_categorized boolean NOT NULL DEFAULT false,
    description text,
    status text NOT NULL DEFAULT 'pending',
    approved_by_employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,
    approved_at timestamptz,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT general_expenses_amount_chk CHECK (amount > 0),
    CONSTRAINT general_expenses_tax_chk CHECK (tax_amount >= 0),
    CONSTRAINT general_expenses_status_chk CHECK (status IN ('pending','approved','rejected','posted')),
    CONSTRAINT general_expenses_approved_chk CHECK ((status <> 'approved' AND approved_at IS NULL) OR (status = 'approved' AND approved_at IS NOT NULL)),
    CONSTRAINT general_expenses_deleted_at_chk CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL))
  );`,
  "CREATE INDEX IF NOT EXISTS general_expenses_vendor_id_idx ON general_expenses(vendor_id);",
  "CREATE INDEX IF NOT EXISTS general_expenses_account_id_idx ON general_expenses(account_id);",
];
