export const invoicesStatements = [
  `CREATE TABLE IF NOT EXISTS invoices (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_number bigserial UNIQUE,
    customer_id uuid NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE RESTRICT,
    estimate_id uuid REFERENCES estimates(id) ON DELETE SET NULL,
    workflow_status text NOT NULL DEFAULT 'draft',
    payment_status text NOT NULL DEFAULT 'unpaid',
    invoice_date date NOT NULL DEFAULT CURRENT_DATE,
    due_date date,
    tax_rate numeric(6,4) NOT NULL DEFAULT 0.06,
    notes text,
    internal_notes text,
    created_by_employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,
    sent_at timestamptz,
    voided_at timestamptz,
    voided_by_employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,
    void_reason text,
    deleted_at timestamptz,
    deleted_by_employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,
    locked boolean NOT NULL DEFAULT false,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT invoices_workflow_status_chk CHECK (workflow_status IN ('draft','sent','void','deleted')),
    CONSTRAINT invoices_payment_status_chk CHECK (payment_status IN ('unpaid','partial','paid')),
    CONSTRAINT invoices_due_date_chk CHECK (due_date IS NULL OR due_date >= invoice_date),
    CONSTRAINT invoices_deleted_chk CHECK ((workflow_status <> 'deleted' AND is_deleted = false AND deleted_at IS NULL) OR (workflow_status = 'deleted' AND is_deleted = true AND deleted_at IS NOT NULL)),
    CONSTRAINT invoices_tax_rate_chk CHECK (tax_rate >= 0 AND tax_rate <= 1)
  );`,
  "CREATE INDEX IF NOT EXISTS invoices_customer_id_idx ON invoices(customer_id);",
  "CREATE INDEX IF NOT EXISTS invoices_job_id_idx ON invoices(job_id);",
  "CREATE INDEX IF NOT EXISTS invoices_estimate_id_idx ON invoices(estimate_id);",

  `CREATE TABLE IF NOT EXISTS invoice_line_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id uuid NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    service_catalog_item_id uuid REFERENCES service_catalog(id) ON DELETE SET NULL,
    description text NOT NULL,
    quantity numeric(12,2) NOT NULL DEFAULT 1,
    unit_price numeric(12,2) NOT NULL DEFAULT 0,
    is_taxable boolean NOT NULL DEFAULT true,
    line_total numeric(12,2) GENERATED ALWAYS AS (round(quantity * unit_price, 2)) STORED,
    sort_order integer,
    CONSTRAINT invoice_line_items_qty_chk CHECK (quantity > 0),
    CONSTRAINT invoice_line_items_unit_price_chk CHECK (unit_price >= 0)
  );`,
  "CREATE INDEX IF NOT EXISTS invoice_line_items_invoice_id_idx ON invoice_line_items(invoice_id);",
];
