export const jobsStatements = [
  `CREATE TABLE IF NOT EXISTS jobs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    job_number bigserial UNIQUE,
    customer_id uuid NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    job_type text NOT NULL,
    priority text NOT NULL DEFAULT 'normal',
    status text NOT NULL DEFAULT 'scheduled',
    scheduled_start timestamptz,
    scheduled_end timestamptz,
    completed_at timestamptz,
    location_street_address text,
    location_city text,
    location_state_code text,
    location_zip text,
    location_latitude numeric(10,7),
    location_longitude numeric(10,7),
    description text,
    customer_notes text,
    internal_notes text,
    created_by_employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT jobs_job_type_chk CHECK (job_type IN ('repair','maintenance','diagnostic','installation','emergency')),
    CONSTRAINT jobs_priority_chk CHECK (priority IN ('emergency','high','normal','low')),
    CONSTRAINT jobs_status_chk CHECK (status IN ('scheduled','in_progress','completed','cancelled')),
    CONSTRAINT jobs_completed_at_chk CHECK ((status <> 'completed' AND completed_at IS NULL) OR (status = 'completed' AND completed_at IS NOT NULL)),
    CONSTRAINT jobs_schedule_range_chk CHECK (scheduled_end IS NULL OR scheduled_start IS NULL OR scheduled_end >= scheduled_start),
    CONSTRAINT jobs_deleted_at_chk CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL))
  );`,
  "CREATE INDEX IF NOT EXISTS jobs_customer_id_idx ON jobs(customer_id);",

  `CREATE TABLE IF NOT EXISTS job_assignments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    employee_id uuid NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
    assignment_role text NOT NULL DEFAULT 'assistant',
    assigned_at timestamptz NOT NULL DEFAULT now(),
    assigned_by_employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,
    CONSTRAINT job_assignments_role_chk CHECK (assignment_role IN ('lead','assistant')),
    CONSTRAINT job_assignments_unique UNIQUE(job_id, employee_id)
  );`,
  "CREATE INDEX IF NOT EXISTS job_assignments_job_id_idx ON job_assignments(job_id);",
  "CREATE INDEX IF NOT EXISTS job_assignments_employee_id_idx ON job_assignments(employee_id);",

  `CREATE TABLE IF NOT EXISTS schedule_blocks (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id uuid NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
    job_id uuid REFERENCES jobs(id) ON DELETE SET NULL,
    block_type text NOT NULL,
    start_time timestamptz NOT NULL,
    end_time timestamptz NOT NULL,
    notes text,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT schedule_blocks_type_chk CHECK (block_type IN ('job','time_off','blocked','available')),
    CONSTRAINT schedule_blocks_time_chk CHECK (end_time > start_time),
    CONSTRAINT schedule_blocks_deleted_at_chk CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL))
  );`,
  "CREATE INDEX IF NOT EXISTS schedule_blocks_employee_id_idx ON schedule_blocks(employee_id);",
  "CREATE INDEX IF NOT EXISTS schedule_blocks_job_id_idx ON schedule_blocks(job_id);",

  `CREATE TABLE IF NOT EXISTS job_photos (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    photo_url text NOT NULL,
    caption text,
    uploaded_by_employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT job_photos_deleted_at_chk CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL))
  );`,
  "CREATE INDEX IF NOT EXISTS job_photos_job_id_idx ON job_photos(job_id);",
];
